Create Database Walmart;
USE Walmart;
SELECT*FROM Walmart;

-- Total weekly sales across all stores
SELECT SUM(Weekly_Sales) AS Total_Sales
FROM walmart;

-- Average weekly sales 
SELECT AVG(Weekly_Sales) AS Average_Weekly_Sales
FROM walmart;

-- Maximum and Minimum weekly sales
SELECT
MAX(Weekly_Sales) AS Maximum_Sales,
MIN(Weekly_Sales) AS Minimum_Sales
FROM walmart;

-- Count total number of stores
SELECT COUNT(DISTINCT Store) AS Total_Stores
FROM walmart;

-- Total revenue generated by each store
SELECT
Store,
SUM(Weekly_Sales) AS Total_Revenue
FROM walmart
GROUP BY Store
ORDER BY Total_Revenue DESC;

-- Rank stores by total sales
SELECT
Store,
SUM(Weekly_Sales) AS Total_Sales
FROM walmart
GROUP BY Store
ORDER BY Total_Sales DESC;

-- Top 5 performing stores
SELECT
Store,
SUM(Weekly_Sales) AS Total_Sales
FROM walmart
GROUP BY Store
ORDER BY Total_Sales DESC
LIMIT 5;

-- Bottom 5 performing stores
SELECT
Store,
SUM(Weekly_Sales) AS Total_Sales
FROM walmart
GROUP BY Store
ORDER BY Total_Sales
LIMIT 5;

